-- Generated by tools/conditional_alignment.py — do not edit by hand.
return {
  {
    stack = "panglia_planet",
    anchor = "panglia_planet",
    section = "surface-property-name",
    key = "temperature-celcius",
    text = "温度（°C）",
  },
  {
    stack = "pelagos",
    anchor = "pelagos",
    section = "entity-description",
    key = "heavy-gun-turret",
    text = "钛合金强化后的重型机枪炮塔。\n 射速是标准版的三倍，射程相同且防护能力大幅提升，完美适用于高强度防御场景。",
  },
  {
    stack = "pelagos",
    anchor = "pelagos",
    section = "entity-name",
    key = "canex-excavator",
    text = "柴油挖掘机",
  },
  {
    stack = "pelagos",
    anchor = "pelagos",
    section = "item-name",
    key = "canex-excavator",
    text = "柴油挖掘机",
  },
  {
    stack = "pelagos",
    anchor = "pelagos",
    section = "technology-description",
    key = "canex-excavator",
    text = "利用液体燃料动力来挖掘水道。",
  },
  {
    stack = "pelagos",
    anchor = "pelagos",
    section = "technology-description",
    key = "heavy-gun-turret",
    text = "钛合金强化过后的重型机枪炮塔射速是标准版的三倍，射程相同且防护能力大幅提升，完美适用于高强度防御场景。",
  },
  {
    stack = "pelagos",
    anchor = "pelagos",
    section = "technology-name",
    key = "canex-excavator",
    text = "柴油挖掘机",
  },
}
